version: '3'

services:
  database:
    container_name: daily_assistant_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: daily_assistant_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
    restart: on-failure
    networks:
      - my_network

#  application:
#    container_name: daily_assistant_app
#    restart: on-failure
#    image: ~~~~
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/daily_assistant_db?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: "root"
#      SPRING_DATASOURCE_PASSWORD: "1234"
#    depends_on:
#      - database
#    networks:
#      - my_network

networks:
  my_network: