version: '3'

services:
  database:
    container_name: general_board_db
    image: mysql
    environment:
      MYSQL_DATABASE: general_board_db
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]

    networks:
      - my_network

  application:
    container_name: general_board-app
    restart: on-failure
    image: hangyeoleom/user:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - my_network

networks:
  my_network: